# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-19 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('sku', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Active', max_length=264)),
            ],
        ),
    ]
